version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  # backend:
  #   build:
  #     context: ./backend
  #   command: go run main.go
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: password
  #     DB_NAME: library
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./backend:/app
  #   working_dir: /app
  # frontend:
  #   build:
  #     context: ./frontend
  #   command: go run main.go
  #   environment:
  #     API_URL: http://backend:8080
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   working_dir: /app
volumes:
  db_data:
