services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      dockerfile: ./build/backend/Dockerfile
      context: .
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "8182:8080"
  #   volumes:
  #     - ./backend:/app
  #   working_dir: /app
  frontend:
    build:
      dockerfile: ./build/frontend/Dockerfile
      context: .
    depends_on:
      - backend
    environment:
      - BACKEND_URI=http://backend:8080
    ports:
      - "4000:4000"

volumes:
  db_data:
